// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_article_column: dynamic(() => import("./BlogArticleColumn")),
  hero: dynamic(() => import("./Hero")),
  text_image: dynamic(() => import("./TextImage")),
};
